on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build the docker image
      run: docker build --build-arg PATCH_VERSION=${{ github.run_number }} -t "${{ secrets.DOCKERHUB_USERNAME }}/maven_jar_artifact:${{ github.run_number }}" .

    - name: run docker image
      run: docker run --name "hello" "${{ secrets.DOCKERHUB_USERNAME }}/maven_jar_artifact:${{ github.run_number }}"

    - name: push docker image
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && docker push ${{ secrets.DOCKERHUB_USERNAME }}/maven_jar_artifact:${{ github.run_number }}

    - name: deploy on ec2
      run: run: echo "${{ secrets.SSH_KEY }}" > my_key.pem && chmod 600 private_key && \
                ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-51-20-86-247.eu-north-1.compute.amazonaws.com '
              cd ~/
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/maven_jar_artifact
              docker run --name "hello" ${{ secrets.DOCKERHUB_USERNAME }}/maven_jar_artifact
             '
